version: 2

models:
  - name: int_order_details
    columns:
      - name: order_id
        tests:
          - not_null

  - name: int_order_enriched 
    columns:
      - name: customer_id
        tests:
          - not_null

  - name: int_order_payments_agg
    columns:
      - name: order_id
        tests:
          - not_null